name: nicehash_calc_sa
description: Free NiceHash calculator for South Africa
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^4.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  in_app_purchase: ^3.1.11
  flutter_local_notifications: ^16.3.0

flutter:
  uses-material-design: true
